# This is a basic workflow to help you get started with Actions

name: ci-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-stage-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      VERSION:

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade -r requirements.txt

      - name: Run the build script
        id: runbuild
        shell: bash
        run: |
            VERSION=$(invoke version)
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

            echo "Building $VERSION"
            invoke build
            ls -al dist

      - name: Check output
        shell: bash
        run: |
          echo "Do we get the output value here?"
          echo "--> ${{ steps.runbuild.outputs.VERSION }}"
          echo "What about here -->" $VERSION

      - name: Save workflow artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ steps.runbuild.outputs.VERSION }}
          path: dist/my_archive-${{ steps.runbuild.outputs.VERSION }}.zzz
