
name: deploy

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      release:
        description: Do a release-mode build
        default: false
        type: boolean

env:
  RELEASE: "${{ inputs.release }}"

jobs:
  build-stage-1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: check environment
        run: |
          echo "RELEASE: $RELEASE"

      - uses: actions/checkout@v3
